//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QLGVModel", "FK_BoMon_Khoa", "Khoa", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(_1191021127.QuanLyGiaoVien.UI.Khoa), "BoMon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.BoMon), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_GiaoVien_BoMon", "BoMon", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(_1191021127.QuanLyGiaoVien.UI.BoMon), "GiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.GiaoVien), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_MonHoc_BoMon", "BoMon", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(_1191021127.QuanLyGiaoVien.UI.BoMon), "MonHoc", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.MonHoc), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(_1191021127.QuanLyGiaoVien.UI.ChucDanh), "ChucDanh_GiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.ChucDanh_GiaoVien), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_ChucDanh_GiaoVien_GiaoVien", "GiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(_1191021127.QuanLyGiaoVien.UI.GiaoVien), "ChucDanh_GiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.ChucDanh_GiaoVien), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_PhanCongGiaoVien_GiaoVien", "GiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(_1191021127.QuanLyGiaoVien.UI.GiaoVien), "PhanCongGiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.PhanCongGV), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_PhanCongGiaoVien_LopHoc", "LopHoc", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(_1191021127.QuanLyGiaoVien.UI.LopHoc), "PhanCongGiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.PhanCongGV), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_PhanCongGiaoVien_MonHoc", "MonHoc", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(_1191021127.QuanLyGiaoVien.UI.MonHoc), "PhanCongGiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.PhanCongGV), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_User_NhomUser", "NhomUser", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(_1191021127.QuanLyGiaoVien.UI.NhomUser), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.User), true)]
[assembly: EdmRelationshipAttribute("QLGVModel", "FK_PhanCongGiaoVien_PhongBan", "PhongBan", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(_1191021127.QuanLyGiaoVien.UI.PhongBan), "PhanCongGiaoVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_1191021127.QuanLyGiaoVien.UI.PhanCongGV), true)]

#endregion

namespace _1191021127.QuanLyGiaoVien.UI
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QLGVEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QLGVEntities object using the connection string found in the 'QLGVEntities' section of the application configuration file.
        /// </summary>
        public QLGVEntities() : base("name=QLGVEntities", "QLGVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLGVEntities object.
        /// </summary>
        public QLGVEntities(string connectionString) : base(connectionString, "QLGVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLGVEntities object.
        /// </summary>
        public QLGVEntities(EntityConnection connection) : base(connection, "QLGVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BoMon> BoMons
        {
            get
            {
                if ((_BoMons == null))
                {
                    _BoMons = base.CreateObjectSet<BoMon>("BoMons");
                }
                return _BoMons;
            }
        }
        private ObjectSet<BoMon> _BoMons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ChucDanh> ChucDanhs
        {
            get
            {
                if ((_ChucDanhs == null))
                {
                    _ChucDanhs = base.CreateObjectSet<ChucDanh>("ChucDanhs");
                }
                return _ChucDanhs;
            }
        }
        private ObjectSet<ChucDanh> _ChucDanhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ChucDanh_GiaoVien> ChucDanh_GiaoVien
        {
            get
            {
                if ((_ChucDanh_GiaoVien == null))
                {
                    _ChucDanh_GiaoVien = base.CreateObjectSet<ChucDanh_GiaoVien>("ChucDanh_GiaoVien");
                }
                return _ChucDanh_GiaoVien;
            }
        }
        private ObjectSet<ChucDanh_GiaoVien> _ChucDanh_GiaoVien;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GiaoVien> GiaoViens
        {
            get
            {
                if ((_GiaoViens == null))
                {
                    _GiaoViens = base.CreateObjectSet<GiaoVien>("GiaoViens");
                }
                return _GiaoViens;
            }
        }
        private ObjectSet<GiaoVien> _GiaoViens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Khoa> Khoas
        {
            get
            {
                if ((_Khoas == null))
                {
                    _Khoas = base.CreateObjectSet<Khoa>("Khoas");
                }
                return _Khoas;
            }
        }
        private ObjectSet<Khoa> _Khoas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LopHoc> LopHocs
        {
            get
            {
                if ((_LopHocs == null))
                {
                    _LopHocs = base.CreateObjectSet<LopHoc>("LopHocs");
                }
                return _LopHocs;
            }
        }
        private ObjectSet<LopHoc> _LopHocs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MonHoc> MonHocs
        {
            get
            {
                if ((_MonHocs == null))
                {
                    _MonHocs = base.CreateObjectSet<MonHoc>("MonHocs");
                }
                return _MonHocs;
            }
        }
        private ObjectSet<MonHoc> _MonHocs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhomUser> NhomUsers
        {
            get
            {
                if ((_NhomUsers == null))
                {
                    _NhomUsers = base.CreateObjectSet<NhomUser>("NhomUsers");
                }
                return _NhomUsers;
            }
        }
        private ObjectSet<NhomUser> _NhomUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhanCongGV> PhanCongGVs
        {
            get
            {
                if ((_PhanCongGVs == null))
                {
                    _PhanCongGVs = base.CreateObjectSet<PhanCongGV>("PhanCongGVs");
                }
                return _PhanCongGVs;
            }
        }
        private ObjectSet<PhanCongGV> _PhanCongGVs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhongBan> PhongBans
        {
            get
            {
                if ((_PhongBans == null))
                {
                    _PhongBans = base.CreateObjectSet<PhongBan>("PhongBans");
                }
                return _PhongBans;
            }
        }
        private ObjectSet<PhongBan> _PhongBans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BoMons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBoMons(BoMon boMon)
        {
            base.AddObject("BoMons", boMon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChucDanhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChucDanhs(ChucDanh chucDanh)
        {
            base.AddObject("ChucDanhs", chucDanh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChucDanh_GiaoVien EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChucDanh_GiaoVien(ChucDanh_GiaoVien chucDanh_GiaoVien)
        {
            base.AddObject("ChucDanh_GiaoVien", chucDanh_GiaoVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GiaoViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGiaoViens(GiaoVien giaoVien)
        {
            base.AddObject("GiaoViens", giaoVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Khoas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhoas(Khoa khoa)
        {
            base.AddObject("Khoas", khoa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LopHocs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLopHocs(LopHoc lopHoc)
        {
            base.AddObject("LopHocs", lopHoc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MonHocs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMonHocs(MonHoc monHoc)
        {
            base.AddObject("MonHocs", monHoc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhomUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhomUsers(NhomUser nhomUser)
        {
            base.AddObject("NhomUsers", nhomUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhanCongGVs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhanCongGVs(PhanCongGV phanCongGV)
        {
            base.AddObject("PhanCongGVs", phanCongGV);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhongBans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhongBans(PhongBan phongBan)
        {
            base.AddObject("PhongBans", phongBan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="BoMon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BoMon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BoMon object.
        /// </summary>
        /// <param name="maBoMon">Initial value of the MaBoMon property.</param>
        public static BoMon CreateBoMon(global::System.Int64 maBoMon)
        {
            BoMon boMon = new BoMon();
            boMon.MaBoMon = maBoMon;
            return boMon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaBoMon
        {
            get
            {
                return _MaBoMon;
            }
            set
            {
                if (_MaBoMon != value)
                {
                    OnMaBoMonChanging(value);
                    ReportPropertyChanging("MaBoMon");
                    _MaBoMon = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaBoMon");
                    OnMaBoMonChanged();
                }
            }
        }
        private global::System.Int64 _MaBoMon;
        partial void OnMaBoMonChanging(global::System.Int64 value);
        partial void OnMaBoMonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenBoMon
        {
            get
            {
                return _TenBoMon;
            }
            set
            {
                OnTenBoMonChanging(value);
                ReportPropertyChanging("TenBoMon");
                _TenBoMon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenBoMon");
                OnTenBoMonChanged();
            }
        }
        private global::System.String _TenBoMon;
        partial void OnTenBoMonChanging(global::System.String value);
        partial void OnTenBoMonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaKhoa
        {
            get
            {
                return _MaKhoa;
            }
            set
            {
                OnMaKhoaChanging(value);
                ReportPropertyChanging("MaKhoa");
                _MaKhoa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaKhoa");
                OnMaKhoaChanged();
            }
        }
        private Nullable<global::System.Int64> _MaKhoa;
        partial void OnMaKhoaChanging(Nullable<global::System.Int64> value);
        partial void OnMaKhoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrungTamDaoTao
        {
            get
            {
                return _TrungTamDaoTao;
            }
            set
            {
                OnTrungTamDaoTaoChanging(value);
                ReportPropertyChanging("TrungTamDaoTao");
                _TrungTamDaoTao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrungTamDaoTao");
                OnTrungTamDaoTaoChanged();
            }
        }
        private global::System.String _TrungTamDaoTao;
        partial void OnTrungTamDaoTaoChanging(global::System.String value);
        partial void OnTrungTamDaoTaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_BoMon_Khoa", "Khoa")]
        public Khoa Khoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Khoa>("QLGVModel.FK_BoMon_Khoa", "Khoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Khoa>("QLGVModel.FK_BoMon_Khoa", "Khoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Khoa> KhoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Khoa>("QLGVModel.FK_BoMon_Khoa", "Khoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Khoa>("QLGVModel.FK_BoMon_Khoa", "Khoa", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_GiaoVien_BoMon", "GiaoVien")]
        public EntityCollection<GiaoVien> GiaoViens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GiaoVien>("QLGVModel.FK_GiaoVien_BoMon", "GiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GiaoVien>("QLGVModel.FK_GiaoVien_BoMon", "GiaoVien", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_MonHoc_BoMon", "MonHoc")]
        public EntityCollection<MonHoc> MonHocs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MonHoc>("QLGVModel.FK_MonHoc_BoMon", "MonHoc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MonHoc>("QLGVModel.FK_MonHoc_BoMon", "MonHoc", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="ChucDanh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChucDanh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ChucDanh object.
        /// </summary>
        /// <param name="maChucDanh">Initial value of the MaChucDanh property.</param>
        public static ChucDanh CreateChucDanh(global::System.Int64 maChucDanh)
        {
            ChucDanh chucDanh = new ChucDanh();
            chucDanh.MaChucDanh = maChucDanh;
            return chucDanh;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaChucDanh
        {
            get
            {
                return _MaChucDanh;
            }
            set
            {
                if (_MaChucDanh != value)
                {
                    OnMaChucDanhChanging(value);
                    ReportPropertyChanging("MaChucDanh");
                    _MaChucDanh = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaChucDanh");
                    OnMaChucDanhChanged();
                }
            }
        }
        private global::System.Int64 _MaChucDanh;
        partial void OnMaChucDanhChanging(global::System.Int64 value);
        partial void OnMaChucDanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenChucDanh
        {
            get
            {
                return _TenChucDanh;
            }
            set
            {
                OnTenChucDanhChanging(value);
                ReportPropertyChanging("TenChucDanh");
                _TenChucDanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenChucDanh");
                OnTenChucDanhChanged();
            }
        }
        private global::System.String _TenChucDanh;
        partial void OnTenChucDanhChanging(global::System.String value);
        partial void OnTenChucDanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoaiChucDanh
        {
            get
            {
                return _LoaiChucDanh;
            }
            set
            {
                OnLoaiChucDanhChanging(value);
                ReportPropertyChanging("LoaiChucDanh");
                _LoaiChucDanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoaiChucDanh");
                OnLoaiChucDanhChanged();
            }
        }
        private global::System.String _LoaiChucDanh;
        partial void OnLoaiChucDanhChanging(global::System.String value);
        partial void OnLoaiChucDanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> HeSoLuong
        {
            get
            {
                return _HeSoLuong;
            }
            set
            {
                OnHeSoLuongChanging(value);
                ReportPropertyChanging("HeSoLuong");
                _HeSoLuong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeSoLuong");
                OnHeSoLuongChanged();
            }
        }
        private Nullable<global::System.Double> _HeSoLuong;
        partial void OnHeSoLuongChanging(Nullable<global::System.Double> value);
        partial void OnHeSoLuongChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh_GiaoVien")]
        public EntityCollection<ChucDanh_GiaoVien> ChucDanh_GiaoVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChucDanh_GiaoVien>("QLGVModel.FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh_GiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChucDanh_GiaoVien>("QLGVModel.FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh_GiaoVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="ChucDanh_GiaoVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChucDanh_GiaoVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ChucDanh_GiaoVien object.
        /// </summary>
        /// <param name="maGiaoVien">Initial value of the MaGiaoVien property.</param>
        /// <param name="maChucDanh">Initial value of the MaChucDanh property.</param>
        public static ChucDanh_GiaoVien CreateChucDanh_GiaoVien(global::System.Int64 maGiaoVien, global::System.Int64 maChucDanh)
        {
            ChucDanh_GiaoVien chucDanh_GiaoVien = new ChucDanh_GiaoVien();
            chucDanh_GiaoVien.MaGiaoVien = maGiaoVien;
            chucDanh_GiaoVien.MaChucDanh = maChucDanh;
            return chucDanh_GiaoVien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaGiaoVien
        {
            get
            {
                return _MaGiaoVien;
            }
            set
            {
                if (_MaGiaoVien != value)
                {
                    OnMaGiaoVienChanging(value);
                    ReportPropertyChanging("MaGiaoVien");
                    _MaGiaoVien = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaGiaoVien");
                    OnMaGiaoVienChanged();
                }
            }
        }
        private global::System.Int64 _MaGiaoVien;
        partial void OnMaGiaoVienChanging(global::System.Int64 value);
        partial void OnMaGiaoVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaChucDanh
        {
            get
            {
                return _MaChucDanh;
            }
            set
            {
                if (_MaChucDanh != value)
                {
                    OnMaChucDanhChanging(value);
                    ReportPropertyChanging("MaChucDanh");
                    _MaChucDanh = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaChucDanh");
                    OnMaChucDanhChanged();
                }
            }
        }
        private global::System.Int64 _MaChucDanh;
        partial void OnMaChucDanhChanging(global::System.Int64 value);
        partial void OnMaChucDanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh")]
        public ChucDanh ChucDanh
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChucDanh>("QLGVModel.FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChucDanh>("QLGVModel.FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ChucDanh> ChucDanhReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChucDanh>("QLGVModel.FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ChucDanh>("QLGVModel.FK_ChucDanh_GiaoVien_ChucDanh", "ChucDanh", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_ChucDanh_GiaoVien_GiaoVien", "GiaoVien")]
        public GiaoVien GiaoVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GiaoVien>("QLGVModel.FK_ChucDanh_GiaoVien_GiaoVien", "GiaoVien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GiaoVien>("QLGVModel.FK_ChucDanh_GiaoVien_GiaoVien", "GiaoVien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GiaoVien> GiaoVienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GiaoVien>("QLGVModel.FK_ChucDanh_GiaoVien_GiaoVien", "GiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GiaoVien>("QLGVModel.FK_ChucDanh_GiaoVien_GiaoVien", "GiaoVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="GiaoVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GiaoVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GiaoVien object.
        /// </summary>
        /// <param name="maGiaoVien">Initial value of the MaGiaoVien property.</param>
        public static GiaoVien CreateGiaoVien(global::System.Int64 maGiaoVien)
        {
            GiaoVien giaoVien = new GiaoVien();
            giaoVien.MaGiaoVien = maGiaoVien;
            return giaoVien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaGiaoVien
        {
            get
            {
                return _MaGiaoVien;
            }
            set
            {
                if (_MaGiaoVien != value)
                {
                    OnMaGiaoVienChanging(value);
                    ReportPropertyChanging("MaGiaoVien");
                    _MaGiaoVien = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaGiaoVien");
                    OnMaGiaoVienChanged();
                }
            }
        }
        private global::System.Int64 _MaGiaoVien;
        partial void OnMaGiaoVienChanging(global::System.Int64 value);
        partial void OnMaGiaoVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.String _GioiTinh;
        partial void OnGioiTinhChanging(global::System.String value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private Nullable<global::System.Int64> _SoDienThoai;
        partial void OnSoDienThoaiChanging(Nullable<global::System.Int64> value);
        partial void OnSoDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaChucDanh
        {
            get
            {
                return _MaChucDanh;
            }
            set
            {
                OnMaChucDanhChanging(value);
                ReportPropertyChanging("MaChucDanh");
                _MaChucDanh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaChucDanh");
                OnMaChucDanhChanged();
            }
        }
        private Nullable<global::System.Int64> _MaChucDanh;
        partial void OnMaChucDanhChanging(Nullable<global::System.Int64> value);
        partial void OnMaChucDanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LuongCoBan
        {
            get
            {
                return _LuongCoBan;
            }
            set
            {
                OnLuongCoBanChanging(value);
                ReportPropertyChanging("LuongCoBan");
                _LuongCoBan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LuongCoBan");
                OnLuongCoBanChanged();
            }
        }
        private Nullable<global::System.Double> _LuongCoBan;
        partial void OnLuongCoBanChanging(Nullable<global::System.Double> value);
        partial void OnLuongCoBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaBoMon
        {
            get
            {
                return _MaBoMon;
            }
            set
            {
                OnMaBoMonChanging(value);
                ReportPropertyChanging("MaBoMon");
                _MaBoMon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaBoMon");
                OnMaBoMonChanged();
            }
        }
        private Nullable<global::System.Int64> _MaBoMon;
        partial void OnMaBoMonChanging(Nullable<global::System.Int64> value);
        partial void OnMaBoMonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TrangThai
        {
            get
            {
                return _TrangThai;
            }
            set
            {
                OnTrangThaiChanging(value);
                ReportPropertyChanging("TrangThai");
                _TrangThai = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrangThai");
                OnTrangThaiChanged();
            }
        }
        private Nullable<global::System.Boolean> _TrangThai;
        public DateTime NgaySinh;
        partial void OnTrangThaiChanging(Nullable<global::System.Boolean> value);
        partial void OnTrangThaiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_GiaoVien_BoMon", "BoMon")]
        public BoMon BoMon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BoMon>("QLGVModel.FK_GiaoVien_BoMon", "BoMon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BoMon>("QLGVModel.FK_GiaoVien_BoMon", "BoMon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BoMon> BoMonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BoMon>("QLGVModel.FK_GiaoVien_BoMon", "BoMon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BoMon>("QLGVModel.FK_GiaoVien_BoMon", "BoMon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_ChucDanh_GiaoVien_GiaoVien", "ChucDanh_GiaoVien")]
        public EntityCollection<ChucDanh_GiaoVien> ChucDanh_GiaoVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChucDanh_GiaoVien>("QLGVModel.FK_ChucDanh_GiaoVien_GiaoVien", "ChucDanh_GiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChucDanh_GiaoVien>("QLGVModel.FK_ChucDanh_GiaoVien_GiaoVien", "ChucDanh_GiaoVien", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_PhanCongGiaoVien_GiaoVien", "PhanCongGiaoVien")]
        public EntityCollection<PhanCongGV> PhanCongGiaoViens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhanCongGV>("QLGVModel.FK_PhanCongGiaoVien_GiaoVien", "PhanCongGiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhanCongGV>("QLGVModel.FK_PhanCongGiaoVien_GiaoVien", "PhanCongGiaoVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="Khoa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Khoa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Khoa object.
        /// </summary>
        /// <param name="maKhoa">Initial value of the MaKhoa property.</param>
        public static Khoa CreateKhoa(global::System.Int64 maKhoa)
        {
            Khoa khoa = new Khoa();
            khoa.MaKhoa = maKhoa;
            return khoa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaKhoa
        {
            get
            {
                return _MaKhoa;
            }
            set
            {
                if (_MaKhoa != value)
                {
                    OnMaKhoaChanging(value);
                    ReportPropertyChanging("MaKhoa");
                    _MaKhoa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaKhoa");
                    OnMaKhoaChanged();
                }
            }
        }
        private global::System.Int64 _MaKhoa;
        partial void OnMaKhoaChanging(global::System.Int64 value);
        partial void OnMaKhoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKhoa
        {
            get
            {
                return _TenKhoa;
            }
            set
            {
                OnTenKhoaChanging(value);
                ReportPropertyChanging("TenKhoa");
                _TenKhoa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenKhoa");
                OnTenKhoaChanged();
            }
        }
        private global::System.String _TenKhoa;
        partial void OnTenKhoaChanging(global::System.String value);
        partial void OnTenKhoaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_BoMon_Khoa", "BoMon")]
        public EntityCollection<BoMon> BoMons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BoMon>("QLGVModel.FK_BoMon_Khoa", "BoMon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BoMon>("QLGVModel.FK_BoMon_Khoa", "BoMon", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="LopHoc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LopHoc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LopHoc object.
        /// </summary>
        /// <param name="maLopHoc">Initial value of the MaLopHoc property.</param>
        public static LopHoc CreateLopHoc(global::System.Int64 maLopHoc)
        {
            LopHoc lopHoc = new LopHoc();
            lopHoc.MaLopHoc = maLopHoc;
            return lopHoc;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaLopHoc
        {
            get
            {
                return _MaLopHoc;
            }
            set
            {
                if (_MaLopHoc != value)
                {
                    OnMaLopHocChanging(value);
                    ReportPropertyChanging("MaLopHoc");
                    _MaLopHoc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaLopHoc");
                    OnMaLopHocChanged();
                }
            }
        }
        private global::System.Int64 _MaLopHoc;
        partial void OnMaLopHocChanging(global::System.Int64 value);
        partial void OnMaLopHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLopHoc
        {
            get
            {
                return _TenLopHoc;
            }
            set
            {
                OnTenLopHocChanging(value);
                ReportPropertyChanging("TenLopHoc");
                _TenLopHoc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLopHoc");
                OnTenLopHocChanged();
            }
        }
        private global::System.String _TenLopHoc;
        partial void OnTenLopHocChanging(global::System.String value);
        partial void OnTenLopHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SiSo
        {
            get
            {
                return _SiSo;
            }
            set
            {
                OnSiSoChanging(value);
                ReportPropertyChanging("SiSo");
                _SiSo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SiSo");
                OnSiSoChanged();
            }
        }
        private Nullable<global::System.Int32> _SiSo;
        partial void OnSiSoChanging(Nullable<global::System.Int32> value);
        partial void OnSiSoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_PhanCongGiaoVien_LopHoc", "PhanCongGiaoVien")]
        public EntityCollection<PhanCongGV> PhanCongGiaoViens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhanCongGV>("QLGVModel.FK_PhanCongGiaoVien_LopHoc", "PhanCongGiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhanCongGV>("QLGVModel.FK_PhanCongGiaoVien_LopHoc", "PhanCongGiaoVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="MonHoc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MonHoc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MonHoc object.
        /// </summary>
        /// <param name="maMonHoc">Initial value of the MaMonHoc property.</param>
        public static MonHoc CreateMonHoc(global::System.Int64 maMonHoc)
        {
            MonHoc monHoc = new MonHoc();
            monHoc.MaMonHoc = maMonHoc;
            return monHoc;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaMonHoc
        {
            get
            {
                return _MaMonHoc;
            }
            set
            {
                if (_MaMonHoc != value)
                {
                    OnMaMonHocChanging(value);
                    ReportPropertyChanging("MaMonHoc");
                    _MaMonHoc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaMonHoc");
                    OnMaMonHocChanged();
                }
            }
        }
        private global::System.Int64 _MaMonHoc;
        partial void OnMaMonHocChanging(global::System.Int64 value);
        partial void OnMaMonHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenMonHoc
        {
            get
            {
                return _TenMonHoc;
            }
            set
            {
                OnTenMonHocChanging(value);
                ReportPropertyChanging("TenMonHoc");
                _TenMonHoc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenMonHoc");
                OnTenMonHocChanged();
            }
        }
        private global::System.String _TenMonHoc;
        partial void OnTenMonHocChanging(global::System.String value);
        partial void OnTenMonHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoTietLyThuyet
        {
            get
            {
                return _SoTietLyThuyet;
            }
            set
            {
                OnSoTietLyThuyetChanging(value);
                ReportPropertyChanging("SoTietLyThuyet");
                _SoTietLyThuyet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoTietLyThuyet");
                OnSoTietLyThuyetChanged();
            }
        }
        private Nullable<global::System.Int32> _SoTietLyThuyet;
        partial void OnSoTietLyThuyetChanging(Nullable<global::System.Int32> value);
        partial void OnSoTietLyThuyetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoTietThucHanh
        {
            get
            {
                return _SoTietThucHanh;
            }
            set
            {
                OnSoTietThucHanhChanging(value);
                ReportPropertyChanging("SoTietThucHanh");
                _SoTietThucHanh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoTietThucHanh");
                OnSoTietThucHanhChanged();
            }
        }
        private Nullable<global::System.Int32> _SoTietThucHanh;
        partial void OnSoTietThucHanhChanging(Nullable<global::System.Int32> value);
        partial void OnSoTietThucHanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoTinChi
        {
            get
            {
                return _SoTinChi;
            }
            set
            {
                OnSoTinChiChanging(value);
                ReportPropertyChanging("SoTinChi");
                _SoTinChi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoTinChi");
                OnSoTinChiChanged();
            }
        }
        private Nullable<global::System.Int32> _SoTinChi;
        partial void OnSoTinChiChanging(Nullable<global::System.Int32> value);
        partial void OnSoTinChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoaiMonHoc
        {
            get
            {
                return _LoaiMonHoc;
            }
            set
            {
                OnLoaiMonHocChanging(value);
                ReportPropertyChanging("LoaiMonHoc");
                _LoaiMonHoc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoaiMonHoc");
                OnLoaiMonHocChanged();
            }
        }
        private global::System.String _LoaiMonHoc;
        partial void OnLoaiMonHocChanging(global::System.String value);
        partial void OnLoaiMonHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaBoMon
        {
            get
            {
                return _MaBoMon;
            }
            set
            {
                OnMaBoMonChanging(value);
                ReportPropertyChanging("MaBoMon");
                _MaBoMon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaBoMon");
                OnMaBoMonChanged();
            }
        }
        private Nullable<global::System.Int64> _MaBoMon;
        partial void OnMaBoMonChanging(Nullable<global::System.Int64> value);
        partial void OnMaBoMonChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_MonHoc_BoMon", "BoMon")]
        public BoMon BoMon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BoMon>("QLGVModel.FK_MonHoc_BoMon", "BoMon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BoMon>("QLGVModel.FK_MonHoc_BoMon", "BoMon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BoMon> BoMonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BoMon>("QLGVModel.FK_MonHoc_BoMon", "BoMon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BoMon>("QLGVModel.FK_MonHoc_BoMon", "BoMon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_PhanCongGiaoVien_MonHoc", "PhanCongGiaoVien")]
        public EntityCollection<PhanCongGV> PhanCongGiaoViens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhanCongGV>("QLGVModel.FK_PhanCongGiaoVien_MonHoc", "PhanCongGiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhanCongGV>("QLGVModel.FK_PhanCongGiaoVien_MonHoc", "PhanCongGiaoVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="NhomUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhomUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhomUser object.
        /// </summary>
        /// <param name="maNhom">Initial value of the MaNhom property.</param>
        public static NhomUser CreateNhomUser(global::System.Int64 maNhom)
        {
            NhomUser nhomUser = new NhomUser();
            nhomUser.MaNhom = maNhom;
            return nhomUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaNhom
        {
            get
            {
                return _MaNhom;
            }
            set
            {
                if (_MaNhom != value)
                {
                    OnMaNhomChanging(value);
                    ReportPropertyChanging("MaNhom");
                    _MaNhom = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaNhom");
                    OnMaNhomChanged();
                }
            }
        }
        private global::System.Int64 _MaNhom;
        partial void OnMaNhomChanging(global::System.Int64 value);
        partial void OnMaNhomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenNhom
        {
            get
            {
                return _TenNhom;
            }
            set
            {
                OnTenNhomChanging(value);
                ReportPropertyChanging("TenNhom");
                _TenNhom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenNhom");
                OnTenNhomChanged();
            }
        }
        private global::System.String _TenNhom;
        partial void OnTenNhomChanging(global::System.String value);
        partial void OnTenNhomChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_User_NhomUser", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("QLGVModel.FK_User_NhomUser", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("QLGVModel.FK_User_NhomUser", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="PhanCongGV")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhanCongGV : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhanCongGV object.
        /// </summary>
        /// <param name="maGiaoVien">Initial value of the MaGiaoVien property.</param>
        /// <param name="maLopHoc">Initial value of the MaLopHoc property.</param>
        /// <param name="maMonHoc">Initial value of the MaMonHoc property.</param>
        /// <param name="maPhongBan">Initial value of the MaPhongBan property.</param>
        public static PhanCongGV CreatePhanCongGV(global::System.Int64 maGiaoVien, global::System.Int64 maLopHoc, global::System.Int64 maMonHoc, global::System.Int64 maPhongBan)
        {
            PhanCongGV phanCongGV = new PhanCongGV();
            phanCongGV.MaGiaoVien = maGiaoVien;
            phanCongGV.MaLopHoc = maLopHoc;
            phanCongGV.MaMonHoc = maMonHoc;
            phanCongGV.MaPhongBan = maPhongBan;
            return phanCongGV;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaGiaoVien
        {
            get
            {
                return _MaGiaoVien;
            }
            set
            {
                if (_MaGiaoVien != value)
                {
                    OnMaGiaoVienChanging(value);
                    ReportPropertyChanging("MaGiaoVien");
                    _MaGiaoVien = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaGiaoVien");
                    OnMaGiaoVienChanged();
                }
            }
        }
        private global::System.Int64 _MaGiaoVien;
        partial void OnMaGiaoVienChanging(global::System.Int64 value);
        partial void OnMaGiaoVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaLopHoc
        {
            get
            {
                return _MaLopHoc;
            }
            set
            {
                if (_MaLopHoc != value)
                {
                    OnMaLopHocChanging(value);
                    ReportPropertyChanging("MaLopHoc");
                    _MaLopHoc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaLopHoc");
                    OnMaLopHocChanged();
                }
            }
        }
        private global::System.Int64 _MaLopHoc;
        partial void OnMaLopHocChanging(global::System.Int64 value);
        partial void OnMaLopHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaMonHoc
        {
            get
            {
                return _MaMonHoc;
            }
            set
            {
                if (_MaMonHoc != value)
                {
                    OnMaMonHocChanging(value);
                    ReportPropertyChanging("MaMonHoc");
                    _MaMonHoc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaMonHoc");
                    OnMaMonHocChanged();
                }
            }
        }
        private global::System.Int64 _MaMonHoc;
        partial void OnMaMonHocChanging(global::System.Int64 value);
        partial void OnMaMonHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaPhongBan
        {
            get
            {
                return _MaPhongBan;
            }
            set
            {
                if (_MaPhongBan != value)
                {
                    OnMaPhongBanChanging(value);
                    ReportPropertyChanging("MaPhongBan");
                    _MaPhongBan = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaPhongBan");
                    OnMaPhongBanChanged();
                }
            }
        }
        private global::System.Int64 _MaPhongBan;
        partial void OnMaPhongBanChanging(global::System.Int64 value);
        partial void OnMaPhongBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThoiGianDay
        {
            get
            {
                return _ThoiGianDay;
            }
            set
            {
                OnThoiGianDayChanging(value);
                ReportPropertyChanging("ThoiGianDay");
                _ThoiGianDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThoiGianDay");
                OnThoiGianDayChanged();
            }
        }
        private Nullable<global::System.Int32> _ThoiGianDay;
        partial void OnThoiGianDayChanging(Nullable<global::System.Int32> value);
        partial void OnThoiGianDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PhanCong
        {
            get
            {
                return _PhanCong;
            }
            set
            {
                OnPhanCongChanging(value);
                ReportPropertyChanging("PhanCong");
                _PhanCong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhanCong");
                OnPhanCongChanged();
            }
        }
        private Nullable<global::System.Boolean> _PhanCong;
        partial void OnPhanCongChanging(Nullable<global::System.Boolean> value);
        partial void OnPhanCongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HocKy
        {
            get
            {
                return _HocKy;
            }
            set
            {
                OnHocKyChanging(value);
                ReportPropertyChanging("HocKy");
                _HocKy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HocKy");
                OnHocKyChanged();
            }
        }
        private global::System.String _HocKy;
        partial void OnHocKyChanging(global::System.String value);
        partial void OnHocKyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NamHoc
        {
            get
            {
                return _NamHoc;
            }
            set
            {
                OnNamHocChanging(value);
                ReportPropertyChanging("NamHoc");
                _NamHoc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NamHoc");
                OnNamHocChanged();
            }
        }
        private Nullable<global::System.Int32> _NamHoc;
        partial void OnNamHocChanging(Nullable<global::System.Int32> value);
        partial void OnNamHocChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_PhanCongGiaoVien_GiaoVien", "GiaoVien")]
        public GiaoVien GiaoVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GiaoVien>("QLGVModel.FK_PhanCongGiaoVien_GiaoVien", "GiaoVien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GiaoVien>("QLGVModel.FK_PhanCongGiaoVien_GiaoVien", "GiaoVien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GiaoVien> GiaoVienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GiaoVien>("QLGVModel.FK_PhanCongGiaoVien_GiaoVien", "GiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GiaoVien>("QLGVModel.FK_PhanCongGiaoVien_GiaoVien", "GiaoVien", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_PhanCongGiaoVien_LopHoc", "LopHoc")]
        public LopHoc LopHoc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LopHoc>("QLGVModel.FK_PhanCongGiaoVien_LopHoc", "LopHoc").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LopHoc>("QLGVModel.FK_PhanCongGiaoVien_LopHoc", "LopHoc").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LopHoc> LopHocReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LopHoc>("QLGVModel.FK_PhanCongGiaoVien_LopHoc", "LopHoc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LopHoc>("QLGVModel.FK_PhanCongGiaoVien_LopHoc", "LopHoc", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_PhanCongGiaoVien_MonHoc", "MonHoc")]
        public MonHoc MonHoc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MonHoc>("QLGVModel.FK_PhanCongGiaoVien_MonHoc", "MonHoc").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MonHoc>("QLGVModel.FK_PhanCongGiaoVien_MonHoc", "MonHoc").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MonHoc> MonHocReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MonHoc>("QLGVModel.FK_PhanCongGiaoVien_MonHoc", "MonHoc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MonHoc>("QLGVModel.FK_PhanCongGiaoVien_MonHoc", "MonHoc", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_PhanCongGiaoVien_PhongBan", "PhongBan")]
        public PhongBan PhongBan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhongBan>("QLGVModel.FK_PhanCongGiaoVien_PhongBan", "PhongBan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhongBan>("QLGVModel.FK_PhanCongGiaoVien_PhongBan", "PhongBan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PhongBan> PhongBanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhongBan>("QLGVModel.FK_PhanCongGiaoVien_PhongBan", "PhongBan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PhongBan>("QLGVModel.FK_PhanCongGiaoVien_PhongBan", "PhongBan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="PhongBan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhongBan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhongBan object.
        /// </summary>
        /// <param name="maPhongBan">Initial value of the MaPhongBan property.</param>
        public static PhongBan CreatePhongBan(global::System.Int64 maPhongBan)
        {
            PhongBan phongBan = new PhongBan();
            phongBan.MaPhongBan = maPhongBan;
            return phongBan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaPhongBan
        {
            get
            {
                return _MaPhongBan;
            }
            set
            {
                if (_MaPhongBan != value)
                {
                    OnMaPhongBanChanging(value);
                    ReportPropertyChanging("MaPhongBan");
                    _MaPhongBan = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaPhongBan");
                    OnMaPhongBanChanged();
                }
            }
        }
        private global::System.Int64 _MaPhongBan;
        partial void OnMaPhongBanChanging(global::System.Int64 value);
        partial void OnMaPhongBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenPhongBan
        {
            get
            {
                return _TenPhongBan;
            }
            set
            {
                OnTenPhongBanChanging(value);
                ReportPropertyChanging("TenPhongBan");
                _TenPhongBan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenPhongBan");
                OnTenPhongBanChanged();
            }
        }
        private global::System.String _TenPhongBan;
        partial void OnTenPhongBanChanging(global::System.String value);
        partial void OnTenPhongBanChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_PhanCongGiaoVien_PhongBan", "PhanCongGiaoVien")]
        public EntityCollection<PhanCongGV> PhanCongGiaoViens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhanCongGV>("QLGVModel.FK_PhanCongGiaoVien_PhongBan", "PhanCongGiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhanCongGV>("QLGVModel.FK_PhanCongGiaoVien_PhongBan", "PhanCongGiaoVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLGVModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="tenDangNhap">Initial value of the TenDangNhap property.</param>
        public static User CreateUser(global::System.String tenDangNhap)
        {
            User user = new User();
            user.TenDangNhap = tenDangNhap;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenDangNhap
        {
            get
            {
                return _TenDangNhap;
            }
            set
            {
                if (_TenDangNhap != value)
                {
                    OnTenDangNhapChanging(value);
                    ReportPropertyChanging("TenDangNhap");
                    _TenDangNhap = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TenDangNhap");
                    OnTenDangNhapChanged();
                }
            }
        }
        private global::System.String _TenDangNhap;
        partial void OnTenDangNhapChanging(global::System.String value);
        partial void OnTenDangNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MatKhau
        {
            get
            {
                return _MatKhau;
            }
            set
            {
                OnMatKhauChanging(value);
                ReportPropertyChanging("MatKhau");
                _MatKhau = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MatKhau");
                OnMatKhauChanged();
            }
        }
        private global::System.String _MatKhau;
        partial void OnMatKhauChanging(global::System.String value);
        partial void OnMatKhauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaNhom
        {
            get
            {
                return _MaNhom;
            }
            set
            {
                OnMaNhomChanging(value);
                ReportPropertyChanging("MaNhom");
                _MaNhom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaNhom");
                OnMaNhomChanged();
            }
        }
        private Nullable<global::System.Int64> _MaNhom;
        partial void OnMaNhomChanging(Nullable<global::System.Int64> value);
        partial void OnMaNhomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private Nullable<global::System.Int64> _SoDienThoai;
        partial void OnSoDienThoaiChanging(Nullable<global::System.Int64> value);
        partial void OnSoDienThoaiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLGVModel", "FK_User_NhomUser", "NhomUser")]
        public NhomUser NhomUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhomUser>("QLGVModel.FK_User_NhomUser", "NhomUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhomUser>("QLGVModel.FK_User_NhomUser", "NhomUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NhomUser> NhomUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhomUser>("QLGVModel.FK_User_NhomUser", "NhomUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NhomUser>("QLGVModel.FK_User_NhomUser", "NhomUser", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
